export const navigations = {
  ROOT: '/',
  SPLASH: '/',
  LOGIN: '/login',
  MISSION: '/mission',
  MISSION_RECORD_WRITE: '/mission/record-write',
  MISSION_COMPLETE_DETAIL: '/mission/complete/detail',
  MISSION_COMPLETE: '/mission/complete',
  GOAL: '/goal',
  GOAL_CONFIRM: '/goal/confirm',
  GOAL_PRE_CHECK: '/goal/pre-check',
  ONBOARDING: '/onboarding',
  HOME: '/home',
  CHAT: '/chat',
  INITIALSETUP: '/initial-setup',
  SUPPORT: '/support',
  AUTH: '/auth',
  ANALYSISRESULT: 'analysis-result',
};
